from mySubPackage2_Module1 import mySubPackage1_Module1_Func1
from mySubPackage2_Module1 import mySubPackage1_Module1_Func2
from mySubPackage2_Module1 import mySubPackage1_Module2_Func1
from mySubPackage2_Module1 import mySubPackage1_Module2_Func2
