from mySubPackage_1 import mySubPackage1_Module1
from mySubPackage_1 import mySubPackage1_Module1
from mySubPackage2 import mySubPackage2_Module1
from mySubPackage2 import mySubPackage2_Module2

from myPackageLevelModule import myPackageLevelModule_Func1